name: Auto Unzip File
on:
  push:
    paths:
      - '**.zip'
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip dan Commit
        run: |
          sudo apt-get install -y unzip
          
          # Cari semua file ZIP di semua subfolder
          find . -name "*.zip" -type f | while read zip_file; do
            echo "Mengekstrak $zip_file ..."
            target_dir=$(dirname "$zip_file")
            if unzip -o "$zip_file" -d "$target_dir"; then
              rm "$zip_file"
            else
              echo "Gagal ekstrak $zip_file"
              exit 1
            fi
          done
          
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git add .
          git commit -m "Auto extract ZIP [skip ci]" && git push origin HEAD:${{ github.ref_name }}
